on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
    paths:
      - '.github/workflows/build.yml'
      - 'global.json'
      - 'Directory.Build.props'
      - 'EntityDb.sln'
      - 'src/**'
      - 'test/**'

name: Build

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Start Redis
        uses: supercharge/redis-github-action@1.2.0
        with:
          redis-version: 7.0.2
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: 5.0.9
          mongodb-replica-set: entitydb
      - name: Install .NET SDK
        uses: actions/setup-dotnet@v2
      - name: Restore Dependencies
        run: dotnet restore EntityDb.sln --locked-mode
      - name: Run Project Tests
        run: dotnet test EntityDb.sln --no-restore -c Debug --collect:"XPlat Code Coverage" -r ./TestResults -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
      - name: Publish Coverage Results
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ./TestResults/**/*.xml
