name: Dependabot Lockfiles
on:
  workflow_dispatch

jobs:
  command:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install .NET SDK
        uses: actions/setup-dotnet@v1
      - name: Update Lock Files
        run: dotnet restore --force-evaluate
      - name: Push Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update lockfiles