on:
  release:
    types:
      - published

name: Publish to Stable

jobs:
  extract:
    name: Extract Release Information
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_release.outputs.tag_name }}
    steps:
      - id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

  stable:
    name: Publish to Stable
    runs-on: ubuntu-latest
    environment: stable
    needs: extract
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Start Redis
        uses: supercharge/redis-github-action@1.2.0
        with:
          redis-version: 6.2.5
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: 5.0.3
          mongodb-replica-set: entitydb
      - name: Install .NET SDK
        uses: actions/setup-dotnet@v1
      - name: Restore Dependencies
        run: dotnet restore EntityDb.sln --locked-mode
      - name: Run Project Tests
        run: dotnet test EntityDb.sln --no-restore -c Debug
      - name: Pack Projects into Nuget Packages
        run: dotnet pack EntityDb.sln --no-restore -c Release /p:Version=${{ needs.extract.outputs.version }}
      - name: Publish to Stable
        run: dotnet nuget push */**.nupkg -s ${{ secrets.NUGET_SOURCE }} -k ${{ secrets.NUGET_API_KEY }}